CREATE DATABASE hostel;
CREATE DATABASE IF NOT EXISTS college;
USE hostel;

DROP DATABASE IF EXISTS college;

CREATE TABLE student(
id INT PRIMARY KEY,
name VARCHAR(50),
age INT NOT NULL
);

INSERT INTO student VALUES(1,"SIURYA",21);
INSERT INTO student VALUES(2,"PRATAP",22);
INSERT INTO student VALUES(3,"SINGH",27);

SELECT * FROM student;

INSERT INTO student VALUES(7,"CR7",40);

SHOW DATABASES;
SHOW TABLES;